title: BUNN Digital Documentation
description: Your guide to integrating with BUNN equipment and APIs!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template


#theme: jekyll-theme-minimal
#remote_theme: pages-themes/hacker@v0.2.0
#remote_theme: pages-themes/cayman@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one


